### ISSUE TITLE
Highlight Questions

### ISSUE THREAD

**Issue by arojasalvarez** [alf10087/SLASP#1]
Highlight questions we think we can match from the HPS.

**Comment by arojasalvarez** [comment]
[pulse2021_data.dictionary_CSV_28.xlsx](https://github.com/alf10087/SLASP/files/8312604/pulse2021_data.dictionary_CSV_28.xlsx)

**Comment by melaniemilligan** [comment]
Here's what I had different and why:

- Q6 (MS): I didn't include this one because our survey didn't ask for marital status
- Q8 (TTHLD_NUMKID): I didn't include this because our survey didn't distinguish b/w adults and kids living in a home
- Q12 (KINDWORK): I didn't include this because our survey didn't distinguish sector of employment
- Q13a-d: I didn't include these because I wasn't sure how to connect them to our survey
- Q19a: I DID include this because I thought it might relate to our question about financial stress?
- Q40c: I didn't include this because I wasn't sure how to connect it to our survey
- Q41c: I didn't include this for same reason as above
